### ISSUE TITLE
Closure-builder can't locate google-closure-library and closure-templates as gulp-task

### ISSUE THREAD

**Issue by iyegoroff** [google/closure-builder#3]
When trying to compile simple .soy template I've got these errors:
```
Not found module: google-closure-library !
Google Closure Library was not found!
Not found module: closure-templates !
Google Closure Template was not found!
```
It seems that the reason of this is `BuildTools.getModulePath` function that assumes google-closure-library and closure-templates modules are located inside closure-builder/node_modules directory. But this is not always true since npm v3.

**Comment by MarkusBordihn** [comment]
The BuildTools.getModulePath search for all registered module paths, so it should not a problem with npm v2 vs npm v3.

But I found out that it doesn't search on the global module path, so all modules which are installed with "npm install -g ..."

I have implemented a fix in 1.0.38, please let me know if this fix works.

If not please tell me your OS and the path where your "google-closure-library" and "closure-templates" folders are located.

**Comment by iyegoroff** [comment]
Just checked latest version. These errors still occur with the following output:

```
Cannot find module: google-closure-library in: [ '/usr/local/lib/node_modules/gulp/bin/node_modules',
  '/usr/local/lib/node_modules/gulp/node_modules',
  '/usr/local/lib/node_modules',
  '/usr/local/node_modules',
  '/usr/node_modules',
  '/node_modules' ]
Google Closure Library was not found!
Cannot find module: closure-templates in: [ '/usr/local/lib/node_modules/gulp/bin/node_modules',
  '/usr/local/lib/node_modules/gulp/node_modules',
  '/usr/local/lib/node_modules',
  '/usr/local/node_modules',
  '/usr/node_modules',
  '/node_modules' ]
Google Closure Template was not found!
```

I'm using Mac OS X El Capitan and the structure of my app looks like this:

my_app/
____ node_modules/
________ closure-builder/
________ closure-templates/
________ google-closure-compiler/
____ src/
____ gulpfile.js (closure-builder is being called from here)

**Comment by MarkusBordihn** [comment]
Thanks for the details. Its seems that this package its currently not 100% compatible with gulp.

As work around you could install "closure-templates" and "google-closure-library" as global package with:
`npm install -g closure-templates`
`npm install -g  google-closure-library`

The "closure-builder" package was designed as stand alone application.
To fully support all features in gulp you would need a gulp plugin version, which is currently not available.

**Comment by iyegoroff** [comment]
Ok. Thank you for clarification.

**Comment by MarkusBordihn** [comment]
The latest version no longer depends on additional npm modules for the closure compilers.
Maybe this fixed this specific issue, if not feel free to create a feature request for an gulp plugin version.
